### ISSUE TITLE
Add different observation types  such velocity/vorticity/pressure probes on surfaces or in the flow field

### ISSUE THREAD

**Issue by cl126162** [dynamicslab/hydrogym#139]
Currently, we use only a very limited number of observations (e.g. lift&drag, TKE, ...) and made them available to the RL agents. However, in literature the majority of current RL applications in fluids use a significantly larger number of velocity/vorticity/pressure probes (on the order of 10 - 200 probes) occasionally distributed across the flow field. For a cylinder, this might look like this:

![image](https://github.com/dynamicslab/hydrogym/assets/56531568/8e814906-5088-4191-8b91-04ac8a73cc33)

To allow comparisons of hydrogym to the literature, we should implement a probing option that outputs observations of  velocity/vorticity/pressure values at given locations (in the flow field and on surfaces).
I suggest to use a flow config arg "flow_observation_type" to specify which kind of value should be returned, e.g, "lift_drag", "probes", and if "probes" is used, another config arg "flow_quantity" might be required to specify which flow quantity should be returned (one or multiple choices of ['velocity', 'vorticity', 'pressure', ...]). Furthermore, an (x-y) coordinate list for should be given, at which location (closest neighboring cell of the given (x-y) pair - I don't think an exact value interpolation based on the surrounding neighbors is necessary) the flow field will be probed.
When using MPI for parallelization, probe values should be gathered by the head rank.

**Comment by jcallaham** [comment]
I have a [branch experimenting](https://github.com/dynamicslab/hydrogym/tree/jc/cyl-velocity-probe) with this, but I have a couple of comments/questions:

1. For the sake of standardization, would it be better to just offer a couple of different options, rather than the "fully configurable" version of velocity/vorticity/pressure at user-defined coordinates?  For instance we could have `"lift_drag"`, `"velocity_probes"`, `"surface_pressure"`, where the velocity probes are a grid of 64 points in the wake and surface pressure is 16 equally distributed points on the cylinder surface or something like that.  Users could always just create their own environment by subclassing `Cylinder` and doing whatever they want.
2. If there are multiple observation types or vector-valued observations (e.g. velocity), should we return observations as flattened vectors or define a ["composite space"](https://gymnasium.farama.org/api/spaces/composite/#composite-spaces) like a dict or tuple of the different arrays.  We can do this, but would just take a little more development effort to rework the code, which currently assumes a flat vector of measurements.
3. The built in [`firedrake.Function.at`](https://www.firedrakeproject.org/_modules/firedrake/function.html#Function.at) can handle MPI-distributed meshes already.  However, this does start to get expensive with larger volumes of probes (e.g. a 128x128 grid takes about 4s for the cylinder).  It's possible that constructing a SciPy interpolant ahead of time and then just doing a gather operation would be more efficient, but this would take some more work to implement, which I'm not all that keen on doing right now.  My vote would be to stick with <100-dimensional observations for the initial release, or we could do a "high-dimensional" grid like that and just warn people about the extra cost, then come back later and try to speed it up.
4. I think that we should do interpolation rather than nearest-neighbors.  The extra computational cost is not that high once you've found the right cell and there's no need to introduce extra numerical error there.

**Comment by cl126162** [comment]
1. True, standardization is quite important as hydrogym should be kind of a reproducible benchmark, so let's offer those three options as default in the release. However, for comparison to the literature, I think it would be convenient for us to easily change the number and locations of the probes (there is no real "standard" in literature regarding this). Let's do this: We start by reproducing other results to validate that hydrogym and the coupled RL agents work comparably with a flexible setup, e.g. by using a some kind of (x-y) coordinate list, and then switch to a "standardized" setup which we keep fixed as a future benchmark.

2. A flattened vector is fine since the agents should know the size of the observation space anyway. So if some kind of network requires individual u,v,p vectors or reshaping formats, then the returned observation can be changed/split/reshaped based on this environment information. I don't think we need to switch to a dict right now - at least not before the next release.

3. That in-built probing tool sounds perfect. Let's stick with it for the moment. The largest number of probes I found in literature was around 150. The 128x128 grid can be part of future work.

4. Sure, then let's do interpolation if there's hardly any extra cost.

5. I only know some papers about the pinball and the cylinder environment. Cavity and Step haven't been subject to RL studies recently, at least I am not aware of some. But here are some links:
Cylinder - ZNMF:
https://arxiv.org/pdf/1808.07664.pdf     approx. 150 probes around cylinder and in the wake

https://arxiv.org/pdf/2202.12685.pdf      5/11 velocity probes in the wake 

https://www.researchgate.net/profile/Wei-Tao-Wu/publication/355066565_Active_control_for_enhancing_vortex_induced_vibration_of_a_circular_cylinder_based_on_deep_reinforcement_learning/links/615d0ca45a481543a887747f/Active-control-for-enhancing-vortex-induced-vibration-of-a-circular-cylinder-based-on-deep-reinforcement-learning.pdf   5/11/151 velocity sensors in the wake

Cylinder - rotating:
https://www.researchgate.net/profile/Shunxiang-Cao/publication/374951156_Reinforcement_learning-based_active_flow_control_of_oscillating_cylinder_for_drag_reduction/links/653929875d51a8012b6f628b/Reinforcement-learning-based-active-flow-control-of-oscillating-cylinder-for-drag-reduction.pdf   --- 11 probes in the wake

https://www.mdpi.com/1996-1073/13/22/5920     12 pressure sensors in the wake

https://arxiv.org/pdf/2402.16543v1.pdf     12 pressure sensors in the wake

Pinball:
https://www.pnas.org/doi/epdf/10.1073/pnas.2004939117      CL&CD of all 3 cylinders

https://arxiv.org/pdf/2304.11526.pdf     CL&CD of all 3 cylinders

https://arxiv.org/pdf/2402.16543v1.pdf    14 pressure sensors around & in the wake

https://iopscience.iop.org/article/10.1088/1742-6596/2367/1/012024/pdf   9 velocity sensors in the wake
