### ISSUE TITLE
Remove coarse meshes

### ISSUE THREAD

**Issue by jcallaham** [dynamicslab/hydrogym#145]
All meshes should be validated against published literature - no more low-quality "training meshes".

**Comment by ReHoss** [comment]
@jcallaham Hello,

From a novice point of view, I do think `coarse` meshes are very useful.
They have the following benefits:

- Very useful for developing and debugging purposes (*e.g.* the user does not wait too long to observe the flow has the correct "natural behaviour" even though not fully spatially converged).
- Since not everyone has large computational resources, coarse meshes increase accessibility.
- While the CFD control community takes care of the quality of the environment, some work is more devoted to the interesting configuration, such as the partial observability or the time delay between the actuation and the sensing. For instance, despite not being spatially converged, the observed dynamics of the Pinball on a coarse grid are still chaotic. Thus, research using those environments remains applicable. Similarly, the actuator/sensor configuration for the Cavity flow is really interesting, regardless of the signal quality.


Best wishes,

**Comment by jcallaham** [comment]
Yes, I take your points, and those are the same reasons why the coarse meshes were there in the first place (although I would maybe disagree that it's worthwhile to study dynamics using a model for which the numerics are not great).

The reason we decided to do this was that we were seeing users run into too much confusion about what to expect when using the coarse meshes - basically, the expectation seemed to be that they work okay, but maybe be slightly less precise or make worse flow field visualizations.  In reality, while they are very useful for debugging and development, they can be much less stable, especially when control is applied.  Our reasoning for removing them was that it would be easier to understand how to work with the package if the supplied configurations actually tended to work and were validated.  That's consistent with one of the goals of Hydrogym, which is to make accurate CFD more accessible to those who want to study dynamics or control of canonical flows without implementing it themselves from scratch.  Of course, it's still possible to configure the time-stepping or actuation signals to destabilize the simulation, but at least it took what seemed to be a major point of confusion off the table.

That said, I still use the coarse meshes all the time for development and debugging - you can just download those files from [here](https://github.com/dynamicslab/hydrogym/tree/398f2269a703b65b2772c96754e3031c6142ff93) for instance and just give the initialization the corresponding mesh name.  Maybe we should at least have those still available on GitHub for download for anyone who wants to do that, although I do still think that removing them from the default available options was the right way to go.  What do you think?

**Comment by ReHoss** [comment]
@jcallaham 
I understand, and I agree that code **stability** should clearly be the priority.

Indeed, under the most recent release of Hydrogym, I have downloaded the coarse meshes from an older commit.  Yes, a link to download the coarse meshes together with a warning to the user could be nice. I am actually not sure how users need those coarse meshes.

By the way, is there a reason why the Pinball never had a medium mesh? Otherwise, could you upload it, if available?:)

Best,
