### ISSUE TITLE
Testcases Completeness

### ISSUE THREAD

**Issue by ludgerpaehler** [dynamicslab/hydrogym#38]
Hey,

Are we now sort of close to test cases completeness @jcallaham ? I have a pretty clear view of the Ray layer and will add all of it in the coming week. Should be able to run a small ray cluster across a few workstations as a proof-of-concept.

- Ludger

**Comment by ludgerpaehler** [comment]
Also just asking - why is the repository already public? 😅

**Comment by jcallaham** [comment]
> Also just asking - why is the repository already public? 😅

Hah, yeah I couldn't add any more collaborators external to Steve's lab org without buying more seats.. I guess I assumed nobody would really pay attention until it was more functional anyway but that might not be totally true.  Have you run into that before?

That's awesome about the ray cluster!  The test cases are coming along - I think the cylinder, pinball, and cavity should be good now, though I plan to test the pinball and cavity later today.  The backwards-facing step will still need a little work to validate, but it's also getting closer.

**Comment by jcallaham** [comment]
Alright, all three of those run without error with an RLLib Train loop (see examples/*/rllib under jc/testcase-validation), though there are still a couple of outstanding issues before I'll be comfortable saying these are ready:

* The cavity reward should be related to fluctuation KE or shear layer pressure oscillation somehow, rather than the pressure directly.
* The `stack_observations` method should be correctly implemented to allow the "observations" to not necessarily be a single `np.ndarray`
* The cavity sensor functionality hasn't been validated and may not be accurate (see Fig. 18 of Barbagallo JFM paper)
* Some of the tests relating to differentiability are failing.

Those are mainly notes to myself, but basically I wouldn't recommend doing anything serious with the cavity yet.

**Comment by jcallaham** [comment]
Almost there... the cavity and step are matching results in the literature, and both work with control.  I just have to make a couple more minor tweaks/fixes and then I'll put up a PR.

**Comment by jcallaham** [comment]
@ludgerpaehler @SamAhnert I'm a little stuck trying to figure out the best way to evaluate the objective function for the step and cavity.  What you're really trying to minimize (at least in the literature on these flows) is the *fluctuation* KE, but to calculate that you need a base state to subtract off.  I can think of three ways to approach this:

1. Precompute the steady state when the flow is initialized (this would add some fairly significant overhead)
2. Save a steady solution in LFS for each mesh resolution that gets loaded on initialization
3. Use the square of the fluctuating measurement as a proxy for KE, which is actually done sometimes in the literature (then we'd just have to store the measurement associated with the steady state).

I don't really like any of these to be honest, but I'm leaning towards option 3.  Any thoughts?
