### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by stwerner97** [dynamicslab/hydrogym#68]
The Docker image seems outdated and I cannot build it successfully. The ``requirements.txt`` file used in the Dockerfile to install dependencies, for example, does not exist anymore in the repository.

**Comment by jcallaham** [comment]
We're reworking the packaging - see the [docs](https://hydrogym.readthedocs.io/en/latest/) for installation recommendations.  Because of the long build times of the Docker image and the duplicate complex-valued installation, probably for most local work (i.e. not distributed on a cluster and if not using complex numbers), using a virtual environment rather than a Docker container will be better.

If you do want to use it, it should be working as of [2a5e50a](https://github.com/dynamicslab/hydrogym/commit/2a5e50aa223757efefd8fb04c2fb4ef6a26e13bd) (main branch)
