### ISSUE TITLE
Cylinder flow rendering with fine mesh fails ?

### ISSUE THREAD

**Issue by ReHoss** [dynamicslab/hydrogym#90]
Hello,

using `overview.ipynb`, the rendering with the fine mesh outputs wrong x and y-axis limits and no data:

![image](https://github.com/dynamicslab/hydrogym/assets/41160498/6ba19b72-7639-4d60-a023-ebfa656f91a3)

This is probably known, as the cell in the notebook is not run ?

**Comment by jcallaham** [comment]
This is actually correct - the "fine" mesh is also on a much larger domain, based on [this paper](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/global-stability-of-base-and-mean-flows-a-general-approach-and-its-applications-to-cylinder-and-open-cavity-flows/EC31631718EB33AA5C671A8F7EAA043C).  But for many applications the "medium" mesh is probably fine for this configuration.  And that particular cell just initializes the flow, so all fields are zero to begin with, which is why there's no data in the plot.
