### ISSUE TITLE
Observation dimension OBS_DIM mismatch for the Pinball flow

### ISSUE THREAD

**Issue by ReHoss** [dynamicslab/hydrogym#92]
Hi,

Pinball `reset` returns a 6 dimensional `list` while the observation space is defined such that `OBS_DIM=1`  from the `PDEBase` class.

Otherwise, I think It should be better to output `np.array` instead of `list` in `gym` environments as this is recommended by environments checkers in general.

Best,

**Comment by jcallaham** [comment]
Good catch! Should be fixed by [95](https://github.com/dynamicslab/hydrogym/pull/95).

The reason we use `list` instead of `ndarray` is that the observation types are not floats, but `AdjFloat`s that can theoretically be used for automatic differentiation.  That's not currently supported, but we hope to explore it in the future, so we'd like to keep the possibility open.
